branches:
  only:
    - master
    - dev

language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2
soluton: Waku.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test
  - cd Waku/ClientApp
  - npm install
  - ng lint
  - ng build --prod
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
