language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2
soluton: Waku.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
